import {backend} from './backend-config.js';
let token='',page=0,status='',selected=null,total=0;
const $=s=>document.querySelector(s);const labels={new:'신규',contacting:'연락 중',closed:'상담 종료'};
function say(text){$('#notice').textContent=text;}
function resetSession(){token='';selected=null;page=0;total=0;$('#record').replaceChildren();$('#requests').replaceChildren();$('#total').textContent='';$('#workspace').hidden=true;$('#login-panel').hidden=false;}
async function api(action,body={}){const r=await fetch(`${backend.url}/functions/v1/pixelline-intake?action=${action}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:backend.anonKey,Authorization:`Bearer ${backend.anonKey}`,'x-admin-token':token},body:JSON.stringify(body),cache:'no-store'});if(r.status===401||r.status===403){resetSession();throw new Error('로그인이 만료되었거나 접근 권한이 없습니다. 다시 로그인해 주세요.');}const d=await r.json();if(!r.ok)throw new Error(d.error||'연결하지 못했습니다. 다시 로그인해 주세요.');return d;}
$('#login').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;say('로그인을 확인하고 있습니다.');try{const r=await fetch(`${backend.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:backend.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email:$('#email').value.trim(),password:$('#password').value})});const d=await r.json();$('#password').value='';if(!r.ok)throw new Error('이메일·비밀번호를 확인해 주세요. 홈페이지 관리자 계정 등록이 먼저 필요합니다.');token=d.access_token;await load();$('#login-panel').hidden=true;$('#workspace').hidden=false;say('관리자 로그인이 확인됐습니다.');}catch(e){token='';say(e.message);}finally{button.disabled=false;}};
async function load(){const d=await api('list',{page,status,search:$('#search').value.trim()});total=d.total;$('#total').textContent=`총 ${total}건`;$('#previous').disabled=page===0;$('#next').disabled=(page+1)*30>=total;$('#requests').replaceChildren();if(!d.items.length)$('#requests').textContent='아직 접수된 상담이 없습니다.';d.items.forEach(item=>{const b=document.createElement('button');b.className='request';const strong=document.createElement('strong');strong.textContent=item.company||'업체 정보 확인 필요';const span=document.createElement('span');span.textContent=`${new Date(item.created_at).toLocaleDateString('ko-KR')} · ${labels[item.status]} · ${item.contact_phone}`;b.append(strong,span);b.onclick=()=>detail(item.id);$('#requests').append(b);});}
async function detail(id){try{const {item}=await api('detail',{id});selected=item;const region=$('#record');region.innerHTML='<h2>접수 상세</h2>';const dl=document.createElement('dl');for(const [name,value] of [['접수일',new Date(item.created_at).toLocaleString('ko-KR')],['제출 방식',item.method],['연락처',item.contact_phone],['보충 정보',item.supplemental_info],['문의 내용',item.message],['삭제 예정일',item.delete_after?new Date(item.delete_after).toLocaleDateString('ko-KR'):'상담 종료 후 6개월']]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value||'없음';dl.append(dt,dd);}region.append(dl);if(item.attachment_path){const b=document.createElement('button');b.className='button';b.textContent='첨부 자료 내려받기';b.onclick=async()=>{try{const {url}=await api('attachment',{id});const a=document.createElement('a');a.href=url;a.rel='noopener noreferrer';a.click();}catch(e){say(e.message);}};region.append(b);}const form=document.createElement('form');for(const [name,key] of [['업체명','company'],['대표자명','owner_name'],['사업장 주소','business_address'],['사업자등록번호','business_number']]){const label=document.createElement('label');label.className='phone';label.textContent=name;const input=document.createElement('input');input.name=key;input.value=item[key]||'';label.append(input);form.append(label);}const state=document.createElement('select');state.name='status';state.setAttribute('aria-label','상담 상태');for(const [v,label]of Object.entries(labels)){const op=document.createElement('option');op.value=v;op.textContent=label;state.append(op);}state.value=item.status;state.style.marginTop='22px';const note=document.createElement('textarea');note.name='internal_note';note.value=item.internal_note||'';note.maxLength=10000;note.placeholder='내부 메모';note.setAttribute('aria-label','내부 메모');const save=document.createElement('button');save.className='button submit';save.textContent='변경 내용 저장';form.append(state,note,save);form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await api('update',{...Object.fromEntries(new FormData(form)),id});say('저장했습니다.');await load();await detail(id);}catch(e){say(e.message);}finally{save.disabled=false;}};region.append(form);}catch(e){say(e.message);}}
async function refresh(){try{await load();}catch(e){say(e.message);}}
$('#refresh').onclick=refresh;$('#previous').onclick=()=>{page=Math.max(0,page-1);refresh();};$('#next').onclick=()=>{page++;refresh();};$('#search-form').onsubmit=e=>{e.preventDefault();page=0;refresh();};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{status=b.dataset.filter;page=0;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));refresh();});
$('#logout').onclick=async()=>{const old=token;resetSession();say('로그아웃했습니다.');try{await fetch(`${backend.url}/auth/v1/logout`,{method:'POST',headers:{apikey:backend.anonKey,Authorization:`Bearer ${old}`}});}catch{}};
